[tool.poetry]
name = "iis"
version = "0.1.0"
description = ""
authors = ["PolnerFilip <filip.polner@student.um.si>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
