name: Data Fetch

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9.13
      uses: actions/setup-python@v4
      with:
        python-version: 3.9.13

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
          pip install  poetry

    - name: Install dependencies
      run: |
        poetry install

    - name: Run script
      run: |
        python -m src.data.fetch_and_process_data

    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github-actions@github.com'
        git add data/*
        git commit -m "action: fetched and processed data"
        git push origin main